// This file was autogenerated by launchbuild.xml
// Creation Time 29.06.2014 14:09:05

(function() {

    //javasript files
    document.write('<script type="text/javascript" src="js/jquery-1.8.3.min.js"></script>');
    document.write('<script type="text/javascript" src="js/jquery-ui/jquery-ui-1.10.3.custom.min.js"></script>');
    document.write('<script type="text/javascript" src="js/jquery-mousewheel-3.0.6/jquery.mousewheel.min.js"></script>');
    document.write('<script type="text/javascript" src="js/jshash-2.2/md5-min.js"></script>');
    document.write('<script type="text/javascript" src="js/jquery-smoothdivscroll/js/jquery.kinetic.js"></script>');
    document.write('<script type="text/javascript" src="js/fancyBox/source/jquery.fancybox.pack.js"></script>');
    document.write('<script type="text/javascript" src="js/fancyBox/source/helpers/jquery.fancybox-thumbs.js"></script>');
    document.write('<script type="text/javascript" src="js/jquery-smoothdivscroll/js/jquery.smoothdivscroll-1.3-min.js"></script>');
    document.write('<script type="text/javascript" src="js/apollomin.js"></script>');

}());
		