<h1>Schnuppertag der Pfadi Gösgen</h1>
<table>
    <tr>
        <th>Datum/Zeit:</th>
        <th>Ort:</th>
        <th>Mitnehmen:</th>
        <th>Kontakt:</th>
    </tr>
    <tr>
        <td>Samstag, 25. März 2017<br>
            14:00-16:00 (4-6 Jährig)<br>
            14:00-17:00 (7-14 Jährig)
        </td>
        <td>Pfadiheim Niedergösgen</td>
        <td>- dem Wetter entsprechende Kleidung<br>
            - gutes Schuhwerk<br>
            - Z'vieri und Z'trinke
        </td>
        <td>
            Raffaele Spielmann v/o Dwalin<br>
            dwalin[at]pfadi-goesgen.ch
        </td>
    </tr>
</table>