<h1>Schnuppertag der Pfadi Gösgen</h1>
<h2>Zeit:</h2>
<p>14.00-16.00 Uhr (Biberstufe: 4-6 Jährige)<br>14.00-17.00 Uhr (Wolfs- u. Pfadistufe: 7-14 Jährige)</p>
<h2>Ort:</h2>
<p>Pfadiheim Niedergösgen</p>
<h2>Kontakt:</h2>
<p>Raffaele Spielmann v/o Dwalin<br>dwalin[at]pfadi-goesgen.ch</p>
<p>Die weltberühmten Angry Birds machen am 25. März Halt in Niedergösgen und benötigen dringend Hilfe:<br>
    Dem Vogel Chuck wurden seine Vogeleier geklaut. Er vermutet den hinterlistigen King Pig dahinter. Wer weiss, was dieser mit seiner Beute vorhat... Auf jeden Fall fehlt von King Pig und den Vogeleiern jede Spur.<br>
    Gelingt es Chuck dank deiner Unterstützung doch noch, die gestohlenen Eier rechtzeitig wiederzufinden?<br><br>
    Das Leiterteam der Pfadi Gösgen freut sich auf zahlreiche neugierige und abenteuerlustige Kinder!
</p>